# .github/workflows/ci-pipeline.yml

name: HTML Static Site CI Pipeline

on:
  push:
    branches:
      - master # Changed from 'main' to 'master'
      - develop # Keep this if you use a 'develop' branch

  pull_request:
    branches:
      - master # Changed from 'main' to 'master'
      - develop

jobs:
  validate-static-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Check for index.html file presence
        run: |
          ls -l
          if [ ! -f index.html ]; then
            echo "Error: index.html not found in the repository root. Please ensure it's there."
            exit 1
          fi
          echo "index.html found. Basic file check passed."